name = "3d-game"
main = "_worker.js"
compatibility_date = "2024-04-28"

[site]
bucket = "./dist"

[build]
command = "npm run build"
cwd = "./"

[env.production]
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[rules]]
type = "Data"
globs = ["**/*.css", "**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp", "**/*.woff", "**/*.woff2", "**/*.ttf", "**/*.otf", "**/*.mp4", "**/*.webm", "**/*.ogg", "**/*.mp3", "**/*.wav"] 